### ISSUE TITLE
Popup menu "flickers" when opened

### ISSUE THREAD

**Issue by jhonatasrm** [mozillabrasil/sumo_live_helper#128]
**Actual behavior**
When the popup menu is opened he "flickers" to adjust the size.

**Expected behavior**
Define the minimum size of the popup menu in that manner he will be opened more smoothly. You can also define the font size, the distance between the components...feel free to implement the solution that you think is best.

🙂

![Popup Menu](https://user-images.githubusercontent.com/8497721/70679639-756bbb00-1c74-11ea-93a9-95fc1fa322bf.png)

**Comment by dannycolin** [comment]
> When the popup menu is opened he "flickers" to adjust the size.

Aha, Strange. It doesn't on Linux. 

> Define the minimum size of the popup menu in that manner he will be opened more smoothly.

What do you mean by that?

Sidenote, I really wonder why the sidebar icon in the popup menu isn't on the same line as the other icons. There's plenty of space.

**Comment by jhonatasrm** [comment]
> What do you mean by that?

If you define a minimum size the popup already starts with a size defined and doesn't need to adjust... But looking with more calm, the popup doesn't change the size to fit the elements, the sidebar icon is a little bit lost...

>Sidenote, I really wonder why the sidebar icon in the popup menu isn't on the same line as the other icons. There's plenty of space.

Yeap.. is a good question...

**Comment by WesleyBranton** [comment]
I think I'm going to add a loading spinner over all of the content until the popup or sidebar loads. I've noticed a lot when working with the mobile content that it takes the computer a fraction of a second to adjust the UI and hide certain elements, so it might be nicer just to cover everything until it's adjusted.
