### ISSUE TITLE
Questions should open in a new tab on Android

### ISSUE THREAD

**Issue by WesleyBranton** [mozillabrasil/sumo_live_helper#133]
On Firefox Android, clicking on a question should open a new tab so that the question list stays open in the background and can easily be returned to.

I already tried setting the `target=_blank` value on the question buttons, but that doesn't work properly. It will open the question in a new tab, but the question list tab appears to get closed for some reason.

**Comment by WesleyBranton** [comment]
So, I've tried a few different ways to open the link in a new tab and each one seems to automatically close the tab for some reason. We can look at this later I suppose.

**Comment by dannycolin** [comment]
> So, I've tried a few different ways to open the link in a new tab and each one seems to automatically close the tab for some reason. We can look at this later I suppose.

Even with `browser.tabs.create()` and the parameter `active` set to `false`?

**Comment by WesleyBranton** [comment]
Sorry, I should have been more specific. I have tried `browser.tabs.create()`, but not with the `active` parameter. I have tried `window.open()` with and without the `_blank` parameter. And I have tried just adding the `target="_blank"` property to the HTML. All of them would open the link, but they would close the question list.

It's obviously opening a new tab, since without any of the options above you can press the back button to get back to the question list. But with any of the options above you aren't able to hit the back button because it's a new tab. You can also see that momentarily the tab counter increases by one and then decreases again.

It's strange because I've used all of the above implementations before on multiple projects without any issues. It's a strange one.
