### ISSUE TITLE
Update Hungarian localization

### ISSUE THREAD

**Issue by jhonatasrm** [mozillabrasil/sumo_live_helper#139]
**Actual behavior**
Some strings in [messages.json](https://github.com/mozillabrasil/sumo_live_helper/blob/master/src/_locales/hu/messages.json) are in English.

**Expected behavior**
The strings in [messages.json](https://github.com/mozillabrasil/sumo_live_helper/blob/master/src/_locales/hu/messages.json) needs to be localized to Hungarian.

**Comment by meskobalazs** [comment]
I am jumping on this.
