### ISSUE TITLE
"Clear notifications" button doesn't permanently clear the notifications

### ISSUE THREAD

**Issue by WesleyBranton** [mozillabrasil/sumo_live_helper#14]
Clicking the minus button to clear the notifications will clear the counter, until the popup is closed and reopened. In that circumstance, the counter will be reset back to the previous value.

**Comment by jhonatasrm** [comment]
When the popup is opened it does a new search for questions to make sure they are the only (showing the counter). After clicking on "Clear notifications" we can do not show new notifications for X minutes, even opening the popup.

**Comment by WesleyBranton** [comment]
Would it be better to save each item to a list in the Storage API with Title, URL, Timestamp and New attributes? Then the Status attribute can toggled to false when the Clear Notifications button is selected. The next time the extension checks, it could compare the new list to the list existing in storage and use that to calculate the new notification counter.

Since items are only valid for 24 hours, the list could easily be cleaned when the background.js file is opened simply by comparing the current time to the time stored in the Timestamp attribute.

**Comment by jhonatasrm** [comment]
I think it's a good solution, it can be useful to do a background search too, showing the already found while searching new ones... 
For now I think we can remove the reloaded result in notification when open the popup menu (treating as a bug) and in the future add the list as you said above to the Storage API.
The notification will appear in each X minutes defined in the Preferences page (search for new questions every X minutes), what you think?  With this will not open every time we open the popup menu.

**Comment by WesleyBranton** [comment]
Although that's not traditionally the function of a "clear notifications" button, that could be a valid fix until something along the lines of what I suggested can be implemented. Storing the items using the Storage API could also help bug #15

**Comment by jhonatasrm** [comment]
If we will look each question will be dependent on a storage list... We can leave this issue dependent on storing the results in a list (Storage API), as we have others that will depend on it... I believe we could create a specific issue and work on a storage list with this in hands solve another issues related. Looks a good start.
