### ISSUE TITLE
Page of Credits

### ISSUE THREAD

**Issue by jhonatasrm** [mozillabrasil/sumo_live_helper#143]
## Summary
I believe will be interesting to have a page to give credits for all the contributors on this extension, maybe this can help in their resume too. 

## Motivation
Recognize all contributors.

## Describe alternatives you've considered
I was thinking of using the same page of the Preferences, but  below of "General"  something like "Credits" and divide the credits by contribution like "Translation to Spanish, Contribution with the code..."

## Additional context
I was thinking of something like this:

![Screen Shot 2020-02-11 at 4 53 08 PM](https://user-images.githubusercontent.com/8497721/74273395-2a5f3a00-4cef-11ea-867d-cfc43eb854dd.png)

Maybe we can use one cool icon on the left side...

**Comment by WesleyBranton** [comment]
I like this idea.

**Comment by dannycolin** [comment]
I also really like it. If we look a Firefox, the font-size for the credits link should be a bit smaller than the default text (0.9em). Also, we could use the "information" icon from https://design.firefox.com/icons/viewer/.

**Comment by jhonatasrm** [comment]
> I also really like it. If we look at Firefox (e.g about:preferences), the font-size for the credits link should be a bit smaller than the default text (0.9em). Also, we could use the "information" icon from https://design.firefox.com/icons/viewer/.

Awesome! I think both are good ideas... I'm thinking about how to present each section inside the credits.

**Comment by WesleyBranton** [comment]
I think we should implement this. We could just make it formatted like the Mozilla credits page (https://www.mozilla.org/credits/), although possibly just as one list instead of alphabet separated because we don't have _that_ many contributors yet.

**Comment by jhonatasrm** [comment]
> I think we should implement this. We could just make it formatted like the Mozilla credits page (https://www.mozilla.org/credits/), although possibly just as one list instead of alphabet separated because we don't have _that_ many contributors yet.

Yes.. looks great and simple to add.

**Comment by WesleyBranton** [comment]
For the credits page, I do not want to pull information from the GitHub repository contributor tab. Instead, I would like to manually reach out to each contributor to get a full name for their credit listing. This will allow contributors to provide a different name than the one provided on their GitHub profile and will also prevent contributors who don't want to be included in the credits from being added.

To reach out to each contributor, I will be going through the pull requests and adding a comment to the most recent pull request for each contributor with information about the credits page and what's required from them. The message will read as follows:

> Hi {NAME}!
> 
> We would once again like to thank you for your contribution to this project. To show our appreciation to all of the awesome people who have helped to make this project so great, we are adding a credits page to the add-on with a list of every contributor that's made a contribution to the project.
> 
> You are one of the individuals that we'd like list in on our credits page!
> 
> If you wish to be listed on the credits page, all we need the name you want to appear on the page. All we need from you is the full name you would like us to add to the page. You can provide us this information as a reply to this comment. To avoid confusion, it would be much appreciated if you could include the name on a new line or surrounded by quotes so that it's clear for us to see.
> 
> If you do not wish to be listed on the credits page, that's fine too (although we'd love to give you the recognition you deserve for your effort). In that case, you can disregard this comment and your name will not be included on the credits page.
> 
> Thanks once again for your contribution to the project and we hope to hear from you soon. If you have any questions, please feel free to reach out.

I would like to do so at some point next week, but wanted to provide a heads up to everyone in case you want any changes to be made to the message prior to it being posting or if you had any other objections.

I'd like to strive for maybe Monday next week (December 28) to give the contributors ample time to get their names added to the list before
