### ISSUE TITLE
Add missing products

### ISSUE THREAD

**Issue by WesleyBranton** [mozillabrasil/sumo_live_helper#146]
There are a few products that are covered by the SUMO website that are not included in the extension. These are:
- Firefox Preview
- Firefox OS (may be removed, see [bug 1613321](https://bugzilla.mozilla.org/show_bug.cgi?id=1613321))
- Firefox for Amazon Devices
- Firefox for Fire TV
- Firefox Private Network Browser-level Protection
- Firefox Private Network Device-level Protection
- Firefox Lockwise
- Firefox Reality
- Firefox Lite
- Firefox Focus

While some of these topics don't receive a huge amount of questions (at least not that I can tell from the English locale), should we add them to the extension to allow contributors to track these categories or would this just be unnecessary traffic for the SUMO API platform?

**Comment by dannycolin** [comment]
> should we add them to the extension to allow contributors to track these categories or would this just be unnecessary traffic for the SUMO API platform?

We could ask Kiki or Giulia if we can get the metrics by products. It should help us make a decision. Also, I think we can already eliminate FirefoxOS  (discontinued product) and Firefox Preview. The latter, we replace Firefox for Android (already had on the nightly channel).

**Comment by jhonatasrm** [comment]
> We could ask Kiki or Giulia if we can get the metrics by products. 

Yes, I think we can do that.

I believe is interesting to have all products, that are available for support on the forum...But I don't know if is good to have so many products on the extension (traffic). Some products don't have so many questions, but we still need to do the query...

P.S. Maybe we can limit the selection of products to do the query if we put all (like 3 products). 🤔

**Comment by dannycolin** [comment]
> P.S. Maybe we can limit the selection of products to do the query if we put all (like 3 products).

I'm not a fan of limiting to 3 products. I prefer to limit the number of products we support if we want to keep the traffic low.

**Comment by WesleyBranton** [comment]
I totally get the excessive traffic argument. However, I would say that the overhead of making an API request is lower than going to the question pages to check that way. To be honest, I think the SUMO platform is good enough to handle, what I assume would be, a relatively low traffic increase.

Plus, we have to ask, how many users would actually add the products to their watchlist? This is purely a guess, but I assume that most of the contributions are made on Firefox variations (desktop, mobile, etc), rather than the other products. So, adding the products to the list would make the extension looked like it's tied in closer to the SUMO platform.

It's something that may be best to ask SUMO leaders first though, to see if they have any opposition to the idea of adding the other (less popular) products.

**Comment by dannycolin** [comment]
> It's something that may be best to ask SUMO leaders first though, to see if they have any opposition to the idea of adding the other (less popular) products.

Indeed. In any case, adding all products doesn't cost us a lot in term of maintenance. I mean it's mostly a copy/paste of code. 

> To be honest, I think the SUMO platform is good enough to handle, what I assume would be, a relatively low traffic increase.

I agree. The requests made currently are a drop in the ocean.

**Comment by jhonatasrm** [comment]
> To be honest, I think the SUMO platform is good enough to handle, what I assume would be, a relatively low traffic increase.

Yes, and extension users will prefer to open the extension instead of the site at all times and look at the questions of each product (almost the same thing).
