### ISSUE TITLE
Enhance our addon visibility and trustworthiness on Mozilla platforms

### ISSUE THREAD

**Issue by dannycolin** [mozillabrasil/sumo_live_helper#147]
## Summary

Ask the SUMO team if we can add our extension to Contributors Tools on support.m.o
More precisely, [this page](https://support.mozilla.org/en-US/kb/answering-questions-support-forum#w_finding-questions). Contact the AMO team about the Recommended program

## Motivation

This could help contributors to find out about our extension especially those that aren't hanging out on IRC with us. Also, if we can get en exception to have a Recommended badge or anything else that could make it looks more official it should help the adoption from Mozillians.

## Describe alternatives you've considered

N/A

## Additional context

Tasks:

- [x] Contact SUMO team to ask if we can add a link to our extension in the Contributors Tools
- [x] Contact AMO on their channel to have more information about the  Recommended program
- [x] Update [Answering Questions KB page](https://support.mozilla.org/en-US/kb/answering-questions-support-forum#w_finding-questions) and wait for Kiki review
- [x] Contact by email the AMO staff to see what would be the best option for our addon to look more official and have more visibility on the addons store.   

**EDIT**

**2020-09-29:** The addons team just launched the Promoted Extension Test Pilots that aims to add a set of new badges. Hopefully, if the test pilots is successful, we could get the verified badge for our extension. This is going to be a paid service but we could discuss with the SUMO and addons team to see if we can get a free pass :).

**Comment by jhonatasrm** [comment]
I liked the idea, maybe we can try to do more too... Idk like, indicate or something like that the SUMO Live Helper to <a href="https://support.mozilla.org/en-US/kb/recommended-extensions-program">Recommended Extensions program</a> when the user accesses the support website, but for doing that we need to see if it is possible. 

I believe the extension has a noble goal and it may actually be recommended if it passes on all tests...

**Comment by dannycolin** [comment]
It could indeed be a good idea. It'd make the extension looks more "official". However, I don't know if the extension needs to check [all the criterias](https://support.mozilla.org/en-US/kb/recommended-extensions-program#w_how-are-recommended-extensions-selected) or a majority of them. I guess we could ask the AMO team. I'll try to ping them this week.

**Comment by dannycolin** [comment]
After, talking with someone from AMO. An extension has to meet all the criteria and Mozilla still has a veto to refuse it. The full documentation on the program can be find [here](https://extensionworkshop.com/documentation/publish/recommended-extensions/#selection).
