### ISSUE TITLE
Allow users to remove specific items from the list

### ISSUE THREAD

**Issue by WesleyBranton** [mozillabrasil/sumo_live_helper#15]
The user should be allowed to delete certain items so that they don't appear on the list.

**Comment by jhonatasrm** [comment]
The main idea is to list all the new questions not answered (for now). I think we can implement this feature in the future at Preferences page. If you have ideas how we could do that or send a PR.. will be amazing.

**Comment by WesleyBranton** [comment]
I was thinking about how this feature could be implemented and each hidden item URL could be saved into storage. Then, when the extension checks for new questions from SUMO, the new list of questions is cross-checked with the ones in the storage. If the item exists in the storage, it's not displayed.

Then, since each unanswered item will only display on SUMO for a maximum of 24 hours, the item URL in storage (which would have to be saved with a timestamp included) could be erased any time after that. This would stop the storage from becoming huge. The list could be checked each time the background.js file starts. That way the list is being cleaned regularly but we aren't wasting resources by checking every time the list is reloaded.

You could also clean the list with a function triggered by the Alarm API, but that's unnecessary and the Alarm API is pretty inconsistent for tasks that are far into the future.

**Comment by jhonatasrm** [comment]
> I was thinking about how this feature could be implemented and each hidden item URL could be saved into storage. Then, when the extension checks for new questions from SUMO, the new list of questions is cross-checked with the ones in the storage. If the item exists in the storage, it's not displayed.
> 
I agree... the search will be more fast and the result too.

So.. I think the next step would be to store the results that were previously searched and with this only replace those who are no longer there when opening the popup menu. A specific issue just to do that? After we can work on issues related to storage list.

**Comment by WesleyBranton** [comment]
It likely wouldn't make the searches any faster, since the search would still need to pull all of the results and then cross-check that with what's stored in the storage, but it would allow for the addition of other functionality in the future. It might be best to create a new issue just to implement this because it's a big change.

If you want, you can assign it to me. I can take a look at it. It shouldn't be too difficult to implement.

**Comment by jhonatasrm** [comment]
I mean faster by the fact we can remove the loading in the popup, being possible to see more quickly the questions, as they are already saved and we can just update the list by doing a background search.

> If you want, you can assign it to me. I can take a look at it. It shouldn't be too difficult to implement.

I will create an issue with expected behavior and current behavior.. and other issues depends on this implementation.

**Comment by WesleyBranton** [comment]
Closing this issue for now. Pull request #21 has a styling rule to distinguish questions that have been opened from newly loaded questions. That nullifies this issue. If it is needed in the future, we can reopen this issue.
