### ISSUE TITLE
Make the "no questions found" screen more appealing

### ISSUE THREAD

**Issue by WesleyBranton** [mozillabrasil/sumo_live_helper#156]
Right now, the screen that displays when there are no questions to answer is pretty boring. We should add some visual flair to the page. I have a working fork of the repo with this sample, although it's based on a very old version of the add-on:

![sample](https://user-images.githubusercontent.com/6621449/87617981-b6362180-c6e6-11ea-94b7-2d6dae3058d5.PNG)

I'm currently working on trying to find out who to contact about usage permissions for that image. There are also other similar images from the SUMO website that we could maybe add on a randomized rotation basis, if that's something that sounds cool.

As far as I can tell, the images were made by Sean Martell, but he didn't respond to my attempts to contact him a few months ago.

**Comment by WesleyBranton** [comment]
**UPDATE:** We cannot use Mozilla brand images because we are not a Mozilla project. We will need to commission or find our own graphics.

**Comment by jhonatasrm** [comment]
Are u sure!? Even though it's a community project directly connected with Mozilla? I think we can e-mail Kiki or someone to talk about it. U already did that?

**Comment by WesleyBranton** [comment]
Yeah, Paul ("Seburo" on SUMO) helped us by contacting someone who is high enough to make the call. It's a no. No big deal though. I'm sure we can find some assets to use. I was already looking at some public domain clipart images and I think we can find one that works for what we want. I'll post some in the Matrix chat when I find some.

**Comment by jhonatasrm** [comment]
That is sad because I really liked the image for all questions answered, but if not possible use... ok
I think we can find something else cool too.

**Comment by WesleyBranton** [comment]
So, I was browsing on a public domain clip art website to see what was available that we could easily use without the need to commission anything and here are some (very rough) layouts. Scaling and positioning can be tweaked. I just kind of threw them together in GIMP to provide samples. They are ordered by what my preference is, with the ones listed first being my favourite.

### 1 - Red T-Rex
![1](https://user-images.githubusercontent.com/6621449/88124706-bc6f4680-cb9b-11ea-8a4f-c029b3ed0223.jpg)
I like this one because it most closely resembles Mozilla's previous (and now virtually non-existent) red dinosaur logo. However, it's not a Mozilla asset. That said, I'm still not sure if this would go against Mozilla's brand trademark, since it may be considered too similar. If this is the one that we consider, I'd probably recommend running it by someone at Mozilla first. It's a single colour image, so the colour of the dinosaur can easily be changed.

### 2 - Another Dinosaur
![2](https://user-images.githubusercontent.com/6621449/88124885-22f46480-cb9c-11ea-95fb-800a02e29bc5.jpg)
This is another nod to the previous Mozilla branding. However, the big difference with this over the previous one is that it's further away from the Mozilla branding. Although the image was not available in SVG format, I'm sure it's not hard to change the colour of the dinosaur, if we want to.

### 3 - Hands
![3](https://user-images.githubusercontent.com/6621449/88124999-59ca7a80-cb9c-11ea-9ef1-8570f0655013.jpg)
This image represents the unity and diversity at Mozilla. Optionally, something could be added to the middle of the hands. It's simple and I like it. It was provided in SVG format, so the hands are very easy to edit, if any changes were recommended or required.

### 4 - Clipboard
![4](https://user-images.githubusercontent.com/6621449/88125188-b7f75d80-cb9c-11ea-92aa-fe0e130a3225.jpg)
This one is pretty standard. It's just a list, which symbolizes the list of questions on SUMO.

### 5 - Fox
![5](https://user-images.githubusercontent.com/6621449/88125281-f1c86400-cb9c-11ea-85b4-ead3d5e62bd8.jpg)
Probably appropriate, since many of the users on the forums are providing support for Firefox-branded products, even though Mozilla does offer more than just Firefox. As with the red dinosaur, I'm not sure how this would be, in terms of trademark. It's not a Mozilla asset and I don't see anywhere that they've trademarked any asset similar to this. As with number 1, it's still probably best to run this by someone at Mozilla, if this is the one we choose to pursue.

### 6 - Coffee/Tea Cup
![6](https://user-images.githubusercontent.com/6621449/88125419-4370ee80-cb9d-11ea-8cba-a59380e558a9.jpg)
Didn't really like this one when I first found it, but I saved it anyway. But the more I look at it, the more I like it. It's a simple image to represent taking a break, which I would hope is universally recognized.

### 7 - Heart
![7](https://user-images.githubusercontent.com/6621449/88125504-6dc2ac00-cb9d-11ea-8d1d-bafb3425290d.jpg)
It's just a heart. A way of showing that we thank the user for helping out with Mozilla's mission, while also representing the diversity at Mozilla.

### 8 - Hand Plant
![8](https://user-images.githubusercontent.com/6621449/88125589-977bd300-cb9d-11ea-973b-d5c09325ff91.jpg)
A nice little image. Represents how the people answering questions are helping to nurture Mozilla and their products so that they can grow and become great.

### 9 - Reading News Paper
![9](https://user-images.githubusercontent.com/6621449/88125683-ce51e900-cb9d-11ea-9773-b501de589fe2.jpg)
Another image representing taking a break. Not much else to say about it.

### 10 - Telephone
![10](https://user-images.githubusercontent.com/6621449/88125734-e9245d80-cb9d-11ea-8358-aea064436b3a.jpg)
Although it's not like users are offering phone support, phones are associated with offering support. It's also a way of representing that the user is waiting to be called upon.

### 11 - Globe
![11](https://user-images.githubusercontent.com/6621449/88125797-0bb67680-cb9e-11ea-9638-df3955be981c.jpg)
An image to remind the people answering questions that they truly are helping people from around the world.

### 12 - Bell
![12](https://user-images.githubusercontent.com/6621449/88125841-24269100-cb9e-11ea-8c63-0ce63e8baf23.jpg)
One of those bells you ring when you want service. Representing that the user waiting for users that need help.

### 13 - Seal with Ball
![13](https://user-images.githubusercontent.com/6621449/88125873-386a8e00-cb9e-11ea-8b81-8ace29587a4d.jpg)
Pretty much included this just because of how cool it would have been to have the Firefox logo replace the ball. Alternatively, we could change the ball into the Earth, which I think might look good as well.

### 14 - Just A Seal
![14](https://user-images.githubusercontent.com/6621449/88125951-6bad1d00-cb9e-11ea-99bf-e75af99cc8f3.jpg)
It's bad luck to have a list with 13 samples, so here's another seal. No reference to Mozilla or support or anything like that. Just a cool animal and there are LOTS of clip art images of seals, for some reason.

**Comment by WesleyBranton** [comment]
I found another potentially good image here.

![Earth](https://user-images.githubusercontent.com/6621449/102837117-10a08000-43f3-11eb-9b71-8735d204d1d1.JPG)
