### ISSUE TITLE
Make unread questions more visible

### ISSUE THREAD

**Issue by WesleyBranton** [mozillabrasil/sumo_live_helper#168]
It can be hard to tell what questions are read and what are unread looking for only what's bold and what's normal text. Some other indicator should be added.

I will add a blue border to the left side of the question to indicate that it's unread.

**Comment by dannycolin** [comment]
If a couple of questions are unread, you'll end up with a long blue border that can be a bit confusing. I think we could implement the idea from the mockup I've done for #130 

Here's the sidebar mockup, but you get the idea of the blue dot for unread questions.
![Sidebar v2](https://user-images.githubusercontent.com/7339076/94175782-28ed1700-fe65-11ea-95fe-c57b4cee6b1b.png)

**Comment by WesleyBranton** [comment]
I do really like the blue dot idea. However, there are some other UI changes that would need to be made in order for that concept to work, so I'm not sure if it's something that could be added right now.

In the meantime, we could give the product icon a border and some slight additional left-side padding. That would make sure that there is a large enough gap between the question separator.

![border](https://user-images.githubusercontent.com/6621449/94178830-9ef37d00-fe69-11ea-845a-d59131df3403.JPG)

But I'm certainly in favour of the dot buttons once a larger UI change is completed.

**Comment by dannycolin** [comment]
> In the meantime, we could give the product icon a border and some slight additional left-side padding. That would make sure that there is a large enough gap between the question separator.

Sounds like a good compromise.
