### ISSUE TITLE
Add Italian locale

### ISSUE THREAD

**Issue by kelimuttu** [mozillabrasil/sumo_live_helper#189]
## Summary

We just enable Italian AAQ for Firefox desktop, Firefox for Android,  Firefox for iOS, and Thunderbird in [Kitsune](https://support.mozilla.org/it/questions). We would like to add the locale in SUMO Live Helper so contributors would be able to get updates quickly. 

## Motivation

So that the Italian contributors can get updates when there's a new question in Italian forum.

**Comment by kelimuttu** [comment]
Wow, this feels like express delivery. Thank you so much @WesleyBranton

**Comment by WesleyBranton** [comment]
You're welcome. I was actually working on bundling the add-on to put an update on AMO when you made this, so it was perfect timing.
