### ISSUE TITLE
Add a contributor at credits

### ISSUE THREAD

**Issue by jhonatasrm** [mozillabrasil/sumo_live_helper#192]
## Summary

Add to the credits in the future update a person who at the very beginning of the project gave some quick tips in relation to it (for previously having made a similar extension).

## Motivation

Credits, so we can remove him from the README, adding to the extension as the others contributors (to be more visible). His nick (he prefers that way) **philipp-sumo**.

Thank you!

**Comment by WesleyBranton** [comment]
I didn't even notice that credit in the README. Thanks for pointing it out.
