### ISSUE TITLE
Some unanswered questions don't appear due to the hardcoded timelimit

### ISSUE THREAD

**Issue by Gersonzao** [mozillabrasil/sumo_live_helper#197]
### Description
Some unanswered questions don't appear even though they are in the product list and checked. Those questions are generally 4 days old or older, I don't know if the extension only looks for recent questions

### Steps to Reproduce
None

**Expected behavior:**
All the unanswered questions would be displayed

**Actual behavior:**
Some of the questions aren't displayed

### System information

* Operating system: Windows 7 SP1 Build 7601
* Firefox version: 102.3 ESR

### Additional Information
None

**Comment by dannycolin** [comment]
> I don't know if the extension only looks for recent questions

It does only look for the questions that are less than 24hrs old. I don't know what the other developers of the extension opinions are but I can tag this issue as a feature request and ask them.
