### ISSUE TITLE
Add NL language as an option

### ISSUE THREAD

**Issue by kelimuttu** [mozillabrasil/sumo_live_helper#202]
## Summary

Add NL as an option in the language selection

## Motivation

We just enabled NL forum in Kitsune for Firefox desktop, iOS, Android, Firefox Enterprise, Focus, and Thunderbird so it'll be great if we can update the language list in the add-on. 

## Describe alternatives you've considered

Unfortunately, there's no other way people can get notifications every time there's a new question in a specific forum they want to follow. 

## Additional context

-

**Comment by Timmaks** [comment]
thank you for filing this, kiki

**Comment by dannycolin** [comment]
Closed by #204
