### ISSUE TITLE
"Refresh" more smooth

### ISSUE THREAD

**Issue by jhonatasrm** [mozillabrasil/sumo_live_helper#23]
**Actual behavior**

By clicking on the icon "Refresh" to update the questions the popup assumes the minimum height of X px and opens again.

**Expected behavior**

By clicking on the  "Refresh" icon to search for new questions the popup should be open in the current size (to not pass the impression of not reloading smoothly).

**Suggestion**

Within the [background.js](https://github.com/mozillabrasil/sumo_live_helper/blob/master/src/js/background.js) set the minimum size of the popup based on the number of saved questions.

e.g. `document.getElementById("").style.minHeight = ...`

**Comment by WesleyBranton** [comment]
Can't we just lock the min-height of the body so that it's always whatever the maximum Firefox browser action popup allows for? I want to say it's 500px maximum, but I'm not entirely sure.

**Comment by jhonatasrm** [comment]
We can do that, but if we have 0 questions shows the message  "Congratulations! All questions have been answered!".

If we keep the minimum height static will be necessary change the distances to show the message of 0 questions...We can see if it will be good that way too, but looks a good solution.
