### ISSUE TITLE
Line below the menu bar getting hidden behind the highlighted question

### ISSUE THREAD

**Issue by jhonatasrm** [mozillabrasil/sumo_live_helper#25]
**Actual behavior**

After open a question in the questions list, she gets highlighted and when uses the scroll bar the line bellow menu bar hides behind the question.

**Steps to reproduce:**

1 - Open the Add-on
2 - Click in "Open" into a question
3 - Return to the Add-on and use the scroll bar until the menu bar partially covers the highlighted question.

**Expected behavior**

When using the scroll bar the line bellow the menu bar needs stay visible all the time.

**Comment by WesleyBranton** [comment]
I can't reproduce. Do you have a screenshot?

**Comment by jhonatasrm** [comment]
Apparently it's just when done scroll down on the add-on.. After less than second returns to normal.

![bug](https://user-images.githubusercontent.com/8497721/62166192-81bf2f00-b2f6-11e9-838e-dda3743e3f5e.png)

**Comment by jhonatasrm** [comment]
Solved in the last updates to add new functionalities. 🙂
