### ISSUE TITLE
Add preferences UI

### ISSUE THREAD

**Issue by WesleyBranton** [mozillabrasil/sumo_live_helper#28]
This will allow users to select how often to check for questions and will allow for the implementation of other features in the future, such as issue #27.

**Comment by jhonatasrm** [comment]
We already have the page Preferences just needing implement and define what kind of settings we can put there initially. I think for now the next step is define the settings, like:

1. Enable browser notification for new question
2. Choose a language ( to search questions.. will be very good to the next SUMO Sprint)
3.  Time in minutes to search for new questions (5, 10, 15, 30..)

In future we can add the product too (maybe in the popup to be more easily to set)...

**Comment by WesleyBranton** [comment]
For now, I think just 2 and 3 need to actually be implemented into the code. Whoever adds the browser notification feature can add the associated options. I'll assign you to this issue, since I see that there is already some existing options UI code in progress.
