### ISSUE TITLE
Separate background script from the popup script

### ISSUE THREAD

**Issue by WesleyBranton** [mozillabrasil/sumo_live_helper#36]
This is a major code change, but would be useful for optimize the code and increase the performance of the extension. Because the popup runs in the background, there is some extra overhead. We may also experience issues implementing features in the future if it's not addressed.

I don't really picture this being a huge task to do and would be willing to handle the code changes. It would likely take a little longer than a lot of the other bug fixes and it would block all other code development until it's completed.

If anyone has any objections to the change, speak up.

**Comment by pikachu1234re** [comment]
İcq No : 743895853 Me helper
