### ISSUE TITLE
Search opened questions in French

### ISSUE THREAD

**Issue by jhonatasrm** [mozillabrasil/sumo_live_helper#60]
**Actual Behavior**
When are changed the products to search for new opened questions in French works only in Firefox for Desktop.

**Expected Behavior**
When the language selected is French keep only the product Firefox for Desktop, while we seek a solution to this issue in the API used or just remove the French language option.

We need discuss about that... What is the best solution temporarily?

**Comment by dannycolin** [comment]
I think we should keep it and just add a notification that currently only Firefox for Desktop is supported for the french language. To extend on that problem see #61.

**Comment by jhonatasrm** [comment]
Looks a good solution too.. I'm thinking in do a temporarily fix soon as possible, so we can release the new version with more products supported, to help with the SUMO Sprint (September 3 - September 17).

**Comment by jhonatasrm** [comment]
Looks the questions in French are made in a different forum, so in the next release we will remove the option to search for questions in French.. since we can't track the new opened questions.

**Comment by dannycolin** [comment]
Yep. I saw that on #sumo. It's very unfortunate :(.
