### ISSUE TITLE
Add ability to search questions in multiple languages

### ISSUE THREAD

**Issue by dannycolin** [mozillabrasil/sumo_live_helper#61]
Lots of volunteers probably speak more than one language. So, I think giving them the ability to search questions in multiple language would make sense.

**Comment by jhonatasrm** [comment]
Sure! We are working on that, the main idea is put all the languages supported at website. We just are thinking in encourage the localization for all languages (supported in the SUMO website) and every new language localized we put a option to search for that language. As we are working to solve some issues with the French language that was localized, more info in the issue #60 .

**Comment by WesleyBranton** [comment]
The functionality of this issue would be identical to issue #48. That should be implemented first and then it would be easier to implement this.
