### ISSUE TITLE
Add localization to Spanish

### ISSUE THREAD

**Issue by jhonatasrm** [mozillabrasil/sumo_live_helper#66]
**Actual behavior**
The strings in [messages.json](https://github.com/mozillabrasil/sumo_live_helper/blob/master/src/_locales/es/messages.json) are in English.

**Expected behavior**
The strings in [messages.json](https://github.com/mozillabrasil/sumo_live_helper/blob/master/src/_locales/es/messages.json) needs to be localized to Spanish.

**Comment by WesleyBranton** [comment]
Complete issue #68 first.
