### ISSUE TITLE
Add localization to Czech

### ISSUE THREAD

**Issue by jhonatasrm** [mozillabrasil/sumo_live_helper#67]
**Actual behavior**
The strings in [messages.json](https://github.com/mozillabrasil/sumo_live_helper/blob/master/src/_locales/cs/messages.json) are in English.

**Expected behavior**
The strings in [messages.json](https://github.com/mozillabrasil/sumo_live_helper/blob/master/src/_locales/cs/messages.json) needs to be localized to Czech.

**Comment by WesleyBranton** [comment]
Complete issue #68 first.
