### ISSUE TITLE
Remove unused locale items

### ISSUE THREAD

**Issue by WesleyBranton** [mozillabrasil/sumo_live_helper#68]
We need to check that all of the strings in each locale file is necessary. In my last edit to the code, it looked like there were some that weren't actually being used anywhere in the code. Getting rid of the extras would reduce the complexity of localization and make it more maintainable in the future.

**Comment by jhonatasrm** [comment]
I agree with you we need review the strings. By reviewing this will be less complex to localize and more maintainable.
