### ISSUE TITLE
Add localization to Hungarian

### ISSUE THREAD

**Issue by jhonatasrm** [mozillabrasil/sumo_live_helper#71]
**Actual behavior**
The strings in [messages.json](https://github.com/mozillabrasil/sumo_live_helper/blob/master/src/_locales/hu/messages.json) are in English.

**Expected behavior**
The strings in [messages.json](https://github.com/mozillabrasil/sumo_live_helper/blob/master/src/_locales/hu/messages.json) needs to be localized to Hungarian.

**Comment by meskobalazs** [comment]
I have just sent a PR: #125

**Comment by jhonatasrm** [comment]
Thank you!
🙂
