### ISSUE TITLE
Plurals are not handled correctly

### ISSUE THREAD

**Issue by MikkCZ** [mozillabrasil/sumo_live_helper#77]
Plurals for several strings are not handled correctly. Currently it supports only two forms - one and everything else. But for example Czech has three forms - one, few (2-4), other (0 and 5 and more). It can be more complex for other languages (see https://developer.mozilla.org/en-US/docs/Mozilla/Localization/Localization_and_Plurals). I am not sure if `browser.i18n`/`chrome.i18n` have a solution for that.

Related issue is that the strings do not use placeholder and instead contact the number with the translated string, which for example does not allow some Czech translations to be made grammatically correct. See https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/i18n/Locale-Specific_Message_reference how the placeholders can be used.

**Comment by MikkCZ** [comment]
Hey @WesleyBranton . Is this extensions still actively developed, please? I see two open PR and I am wondering, if there would be interest in opening one to fix this issue. I am trying to clean my lists on GitHub, so I am ready to either try provide a PR to fix this (if it gets reviewed), or close this issue.

**Comment by jhonatasrm** [comment]
Hello @MikkCZ and @WesleyBranton, 

I'm taking the time to update all my things on GitHub, if any help is needed in review and approval, I'm available.  

About the new versions of SUMO Live Helper, I can help to do the versioning and update the AMO, as well.

Best  Regards,
Jhonatas
