### ISSUE TITLE
Replace the "open" button with an icon button

### ISSUE THREAD

**Issue by WesleyBranton** [mozillabrasil/sumo_live_helper#87]
We should consider replacing the "open" button for the questions with a universally understood icon button. This benefits us because it doesn't require localization and would allow the question title text to be displayed wider (ideal if we implement a sidebar, which is narrower than a popup).

I'm thinking maybe an eye icon or maybe even something as simple as an right arrow icon. It would still be encased in the button, but just be an image instead of text.

This could be included in the changes being made for issue #58.

**Comment by jhonatasrm** [comment]
> I'm thinking maybe an eye icon or maybe even something as simple as an right arrow icon. It would still be encased in the button, but just be an image instead of text.

I totally agree with that, it will be more modern too... I think @dannycolin  is working on that, but we do not define if it will be an eye or a right arrow icon.

**Comment by WesleyBranton** [comment]
I think that the eye is most universally understood for "view", so it probably works best. I can see if I can find a good public domain eye SVG. If not, I'm sure I can throw one together. Who knows, maybe there is an eye SVG file somewhere in the Firefox files.

**Comment by WesleyBranton** [comment]
The icon from Lockwise should work for the button. When we go to do this, we can modify it for a light and dark theme. It's at `chrome://browser/content/aboutlogins/icons/show-password.svg`

**Comment by dannycolin** [comment]
In the mockup I did, I used the "Open in new" icon from the photon icons (https://design.firefox.com/icons/viewer/#open). Most users know it'll open the element/link in a new tab.

**Comment by WesleyBranton** [comment]
I completely forgot about that one. Either one works for me.
